### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received [Function]

### ISSUE THREAD

**Issue by matiosfree** [jfmdev/simple-spellchecker#1]
When I run this code, I get an error.

```
SpellChecker.getDictionary('en-US', function(err, dictionary) {
                        if (!err) {
                            var misspelled = !dictionary.spellCheck('maisonn');

                            if (misspelled) {
                                var suggestions = dictionary.getSuggestions('maisonn');
                            }
                        }
});
```

You need change this line: https://github.com/jfmdev/simple-spellchecker/blob/master/index.js#L37
**{ path: folderPath }**  to **{ path: folder }**

also, **The dicctionary**  to **The dictionary**

**Comment by jfmdev** [comment]
Thanks for you contribution!

I have just make the changes you suggest (sorry it took me so long).

Regards
