### ISSUE TITLE
err: The dictionary could not be read, no file with the name "en-US" could be found

### ISSUE THREAD

**Issue by basile-cluzeau** [jfmdev/simple-spellchecker#11]
Hello,

I tried to use your module but it misses the full path to use correctly fs.exists(...).
Error when getDictionary is used/called in a different folder (i.e. simple-spellchecker is installed in node_modules).

I solved the problem adding this line to getDictionary and getDictionarySync just after folder initialization:
`folder = __dirname + '/' + folder;`

I can't submit a pull request...

Best regards,
Basile

**Comment by jfmdev** [comment]
Thanks for your suggestion, I have just made a commit with that change
