### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by dineshmani** [jfmdev/simple-spellchecker#13]
I'm building my project using webpack. I'm getting Module **not found: Error: Can't resolve 'fs' error**. I have tried many solutions/workarounds, no one is helped me to resolve this issue. Please provide the solutions to solve.

![spellcheck_issue](https://user-images.githubusercontent.com/5707399/46131872-598c1d00-c25a-11e8-8b67-4f3326543e19.png)

Thanks
Dinu

**Comment by jfmdev** [comment]
Hi Dinu, that is an error related to Webpack, which was already reported: https://github.com/webpack-contrib/css-loader/issues/447
