### ISSUE TITLE
Cannot install simple-spellchecker with local artifact repository manager without internet

### ISSUE THREAD

**Issue by devenvag** [jfmdev/simple-spellchecker#16]
Hello,

I have to install simple-spellchecker behind a local artifact repository (Nexus Repository) with no access to internet. The simple-spellchecker package has a depenency to a lib called Damerau-Levenshtein located on github.com on the internet.

So I cannot install simple-spellchecker this way. Please, how I can solve this issue ?

Thanks in advance

**Comment by jfmdev** [comment]
You can install `simple-spellchecker` on a machine with Internet access, then copy the "node_modules" to a USB drive (or similar) and paste it on the local artifact repository (check https://stackoverflow.com/questions/43064107/how-to-install-npm-package-while-offline for more information). Regards
