### ISSUE TITLE
Apply to webview textarea content 

### ISSUE THREAD

**Issue by Robindfuller** [jfmdev/simple-spellchecker#17]
Hi. I would like to enable spellcheck on a textarea inside a webview.  Is this at all possible?

**Comment by jfmdev** [comment]
That depends: if you are building a web application, then you should move this question to some development forum, like StackOverflow; if you are developing a desktop application using Electron, you can use this project as guide: https://github.com/jfmdev/PlainCAT (please note that current version uses `nodehun` as spellchecker library, but if you check the logs you will see that previous versions used `simple-spellchecker`).
