### ISSUE TITLE
Error when trying to install package

### ISSUE THREAD

**Issue by buffet-time** [jfmdev/simple-spellchecker#24]
C:\Users\daniel\Desktop\MDC Dev>npm install simple-spellchecker
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm WARN addRemoteGit  git://github.com/cbaatz/damerau-levenshtein.git resetting remote C:\Users\daniel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-cbaatz-damerau-levenshtein-git-9bffa4c0 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\daniel\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/cbaatz/damerau-levenshtein.git C:\Users\daniel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-cbaatz-damerau-levenshtein-git-9bffa4c0: Cloning into bare repository 'C:\Users\daniel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-cbaatz-damerau-levenshtein-git-9bffa4c0'...
npm ERR! git clone --template=C:\Users\daniel\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/cbaatz/damerau-levenshtein.git C:\Users\daniel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-cbaatz-damerau-levenshtein-git-9bffa4c0: fatal: Unable to look up github.com (port 9418) (No such host is known. )
npm ERR! code 128
npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\daniel\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/cbaatz/damerau-levenshtein.git C:\Users\daniel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-cbaatz-damerau-levenshtein-git-9bffa4c0
npm ERR! Cloning into bare repository 'C:\Users\daniel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-cbaatz-damerau-levenshtein-git-9bffa4c0'...
npm ERR! fatal: Unable to look up github.com (port 9418) (No such host is known. )
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\daniel\AppData\Roaming\npm-cache\_logs\2019-02-26T18_48_54_816Z-debug.log

**Comment by buffet-time** [comment]
@jfmdev I think the issue is that you are using git:// and behind the proxy i use it's resolving incorrectly. 

https://github.com/saltstack/salt-bootstrap/issues/944#issuecomment-242663499

**Comment by jfmdev** [comment]
I think it's  *npm* who is using `git://` by default. But you can try executing `https://github.com/jfmdev/simple-spellchecker.git`

**Comment by buffet-time** [comment]
What exactly do you mean by executing that git url? And how exactly could i automate this so other people don't have to manually execute commands on their end?

**Comment by jfmdev** [comment]
Sorry, the full command was `npm install https://github.com/jfmdev/simple-spellchecker.git`

**Comment by buffet-time** [comment]
Sure many people may not have the issue, I just don't think that 

```
"repository": {
    "type": "git",
    "url": "git+https://github.com/jfmdev/simple-spellchecker.git"
  }
```

git+https is necessary when basically every other package is like

```
"repository": {
    "type": "git",
    "url": "https://github.com/atom/node-spellchecker.git"
  }
```

Unless i'm misunderstanding. But i do know that i'm able to install [node-spellchecker](https://github.com/atom/node-spellchecker/) with no issue through my proxy settings. And basically every npm package. I assume it's not really a problem to make it install more like that package right?

>
