### ISSUE TITLE
Bug: spellchecker doesn't check if zip was extracted without errors

### ISSUE THREAD

**Issue by JLarky** [jfmdev/simple-spellchecker#28]
In https://github.com/jfmdev/simple-spellchecker/blob/45abb90fdbb7fc9cd1c4e297944c7cd0480f9e82/index.js#L42 unzip only has `on('close'` but no `on('error'` and so when using in electron it shows error message to UI instead of returning it to `callback` of `getDictionary`. I got this error when using electron app installed in linux to `/usr/share` thus node_modules was read-only for user, so no dictionary can be unziped

**Comment by jfmdev** [comment]
Hi @JLarky, thanks for reporting the issue. I have just pushed a fix.
