### ISSUE TITLE
dictionary.spellCheck() returns incorrect result

### ISSUE THREAD

**Issue by yuya-oc** [jfmdev/simple-spellchecker#3]
In some words, `spellCheck()` returns `false` even if the word is included in the dictionary file.

```js
var dictionary = SpellChecker.getDictionarySync("en-US");
dictionary.spellCheck('December'); // => 'true' is expected, but 'false' is returned.
```

I can provide some cases as example.

- Incorrect: English, German, Russian, Japanese, November, December
- Correct: Japan, March

**Comment by jfmdev** [comment]
Does this error also occurs when using the CLI tool?

I tried executing: 
 * `node cli.js check "./dict" en-GB December`
 * `node cli.js check "./dict" en-US December`
 * `node cli.js check "./dict" nl-NL December`

And the result were successful:
 * `{ misspelled: false, suggestions: [ 'Decembers', 'December\'s', 'deceiver' ] }`
 * `{ misspelled: false, suggestions: [ 'Decembers', 'December\'s', 'decenter', 'deceiver' ] }`
 * `{ misspelled: false, suggestions: [ 'decenter', 'decimeer' ] }`

**Comment by yuya-oc** [comment]
No. I got same successful results when using the CLI tool.

- node v6.9.1
- npm v3.10.8
- Windows 10 64bit

To make sure, I tried again in REPL. I got following results.

```js
> spellchecker = require('./index');
> spellchecker.getDictionary('en-US', function(err, result) { dict = result; });
> dict.spellCheck('December');
false
> dict.getSuggestions('December');
[ 'December', 'Decembers', 'December\'s', 'decenter', 'deceiver' ]
> dict.checkAndSuggest('December');
{ misspelled: false,
  suggestions: [ 'Decembers', 'December\'s', 'decenter', 'deceiver' ] }
```

**Comment by jfmdev** [comment]
Ok, I have found the source of the error: the methods `getSuggestions()` and `isMisspelled()` are not working correctly when the word is in the dictionary but it starts with an uppercase letter.
I will have a fix delivered by tomorrow.

**Comment by jfmdev** [comment]
Fixed!
