### ISSUE TITLE
Cannot install all dependencies from private registry

### ISSUE THREAD

**Issue by kpainter-atl** [jfmdev/simple-spellchecker#31]
Related to https://github.com/jfmdev/simple-spellchecker/issues/16, but the dependency on `damerau-levenshtein` which is installed from Github makes it difficult to add the `simple-spellchecker` package to a private NPM registry. Having to install the package from Github means our install would fail if we were to get rate-limited by Github or the author deletes the package. 

May I suggest replacing the dependency with https://github.com/tad-lispy/node-damerau-levenshtein which has been updated more recently and has better test coverage.

**Comment by jfmdev** [comment]
Done!

Thanks for the suggestion
