### ISSUE TITLE
Error using import SpellChecker from 'simple-spellchecker'

### ISSUE THREAD

**Issue by DOUGLASMD1** [jfmdev/simple-spellchecker#36]
I'm having this problem when importing the package:

```
browser.js?f28c:177 Uncaught Error: process.binding is not supported
    at Object.process.binding (browser.js?f28c:177)
    at Object.eval (tmp.js?985f:18)
    at eval (tmp.js:764)
    at Object../node_modules/tmp/lib/tmp.js (app.js:15852)
    at __webpack_require__ (app.js:726)
    at fn (app.js:101)
    at Object.eval (index.js?d253:10)
    at eval (index.js:234)
    at Object../node_modules/simple-spellchecker/index.js (app.js:15738)
    at __webpack_require__ (app.js:726)
```

**Comment by chandansaibdb** [comment]
Yes so I am, I'm trying to import the module, it throws this exception error in console.

**Comment by DOUGLASMD1** [comment]
> Yes so I am, I'm trying to import the module, it throws this exception error in console.

@chandansaibdb, did you find any solution for this exception?

**Comment by jfmdev** [comment]
Can your share more information in order to reproduce the bug?  
(e.g. Node version you run, code sample, and so on)

**Comment by DOUGLASMD1** [comment]
I'm using node version v8.10.0. I use this snippet import SpellChecker from 'simple-spellchecker' inside a vuejs component, but it returns this error for me.

**Comment by DOUGLASMD1** [comment]
Here is the code snippet I use:

`<template>
    <div id="conteudo" class="conteudo">
        <div id="pagina" class="pagina">
        </div>
    </div>
</template>

<script>
    import SpellChecker from 'simple-spellchecker'
</script>

<style lang="stylus">
</style>`

**Comment by jfmdev** [comment]
Unfortunately, this library can't be run inside a browser (i.e. you can't use it inside VueJS components) it can only be used with Node.js (i.e. backend code, not frontend).
