### ISSUE TITLE
Integration as a plugin for Obsidian

### ISSUE THREAD

**Issue by daviddev1** [jfmdev/simple-spellchecker#39]
Hello,

Can somebody please help me integrate this into a plugin for the note taking program Obsidian, which runs on Electron?
Currently Obsidian does not have a spellchecking plugin, I don't know why but if this works it would be a great solution until it becomes native to Obsidian.

Thanks,
David

**Comment by jfmdev** [comment]
Hi Daved,

On the readme file there is a small example about Electron's integration: https://github.com/jfmdev/simple-spellchecker#electrons-integration

However you should ask for the Obsidian's community about how to wrap that into a plugin for the Obsidian app.

Best regards
