### ISSUE TITLE
MIT or Apache 2.0 open source license

### ISSUE THREAD

**Issue by jasonblais** [jfmdev/simple-spellchecker#4]
Thanks for sharing this project! 

We'd love to use it as part of the Mattermost open source project (https://www.mattermost.org/) in our [Desktop App](https://github.com/mattermost/desktp) (which uses an [Apache 2.0 license](https://github.com/yuya-oc/desktop/blob/ab7e41c66b3f7b506eb373d099eccd6436ba2d20/LICENSE)). 

Would you consider adding either an [MIT](https://opensource.org/licenses/MIT) or an [Apache 2.0](https://opensource.org/licenses/Apache-2.0) license to your project? 

If you use either an MIT license or an Apache 2.0 license it would make it easy to add your work to other open source projects, and we'd love to include your work in ours. 

Thanks kindly for your consideration.

**Comment by jfmdev** [comment]
Hi Jason,

I will consider your suggestion, although I'm not really a fan of copyleft licenses that allow your software to be re-licensed as closed source.

But please note that this project is licensed under [**Lesser** GPL 3](https://www.gnu.org/licenses/lgpl-3.0.html), which means that the library can be used in either non-GPL projects or proprietary software.

**Comment by jasonblais** [comment]
According to the Apache 2.0 documentation, it looks like GNU LPGL software cannot be included within Apache products. These includes the "Lesser GPL 3" that you referenced. The [Mattermost Desktop](https://github.com/mattermost/desktop), which we were considering to add the simple-spellchecker project currently has an Apache v2 license.

http://www.apache.org/legal/resolved.html#category-x

We'd really love to add your work as part of the Mattermost Desktop open source project, but also understand if you don't feel comfortable using an MIT or Apache v2 license.

**Comment by jfmdev** [comment]
Hi Jason,

Indeed, you can't mix code between Apache 2.0 and LGPL v3, however you can include a LGPL library in you Apache product as long as: 
 1. You release as LGPL any change made to the original LGPL library.
 2. The linking (between the Apache product and the LGPL library) should be dynamically (which is the case for Node.js).

They are similar discussion in StackOverflow that confirm that is okay to include a LGPL library in a non-GPL project (which is, at the end, the whole purpose of the LGPL license):
 * http://stackoverflow.com/questions/104968/can-i-use-lgpl-library-in-bsd-x11-licensed-project
 * http://stackoverflow.com/questions/13229768/lgpl-license-and-shared-libraries?rq=1
 * http://stackoverflow.com/questions/1910979/using-lgpl-library-in-a-commercial-java-application?rq=1
