### ISSUE TITLE
Does not work well under windows

### ISSUE THREAD

**Issue by hancao97** [jfmdev/simple-spellchecker#42]
The spellCheck method always returns false on windows, not on macs.

**Comment by jfmdev** [comment]
@hancao97 Can you be more specific? Maybe sharing the code you are using, the error message you are getting or the language you are translating?

> I have just run the testing file (`npm run test`) on both Windows 10 and Windows 11 and all functions seems to be working fine.

**Comment by jfmdev** [comment]
Closed due to inactivity.
