### ISSUE TITLE
Set Word List not persisting After Closing Electron

### ISSUE THREAD

**Issue by alaksandarjesus** [jfmdev/simple-spellchecker#49]
Below are my test cases

articel     
this is a sample text
beolw

The code gives suggestion for articel (misspelled).

If I add articel to dictionary (though it is wrong), it is added and does not show error on next attempt.

Close the electron app

run npm start

test with the same sample

the articel is throwing error.

**Expected:**

It should not throw error, because it was added to word list on first attempt.

**Comment by jfmdev** [comment]
Hi @alaksandarjesus,  
Yes, that's expected, the `setWordList` function should be called every time you open the application.  
The library doesn't supports adding new words to the dictionary files.
